<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Danh sch a ch</name>
   <tag></tag>
   <elementGuidId>8b38b05e-b905-4245-869f-8e7f14a3cec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.site_account_info > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='siteNav-account']/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8846af2-60c1-44d6-b580-073c87c0ef50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/addresses</value>
      <webElementGuid>89bd3dc6-aee1-4b46-977a-44f7cabc0b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danh sách địa chỉ</value>
      <webElementGuid>16d0e877-f200-4d27-a5bf-6f8ce25e37d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNav-account&quot;)/div[@class=&quot;site_account_panel_list&quot;]/div[@class=&quot;site_account_info&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>9394c289-b9f7-409a-bd47-e26874ef2ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siteNav-account']/div/div/ul/li[3]/a</value>
      <webElementGuid>ceb0a2fd-652d-4db4-954e-a299be551b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Danh sách địa chỉ')]</value>
      <webElementGuid>b03d82fb-1c0e-4037-b0cd-af246145884c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản của tôi'])[1]/following::a[1]</value>
      <webElementGuid>3294c6af-2f69-4e6b-af9c-d6313ce25db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin tài khoản'])[1]/following::a[2]</value>
      <webElementGuid>02c3edf1-a36a-4460-a69b-dcba607b61d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng xuất'])[1]/preceding::a[1]</value>
      <webElementGuid>6e4200af-2656-4fb8-8bdd-2d6278d66c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TỔNG TIỀN:'])[1]/preceding::a[5]</value>
      <webElementGuid>6289c002-664e-48fc-bbf3-d43ad992c4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Danh sách địa chỉ']/parent::*</value>
      <webElementGuid>a57a31ac-f98c-4063-9725-97356b23d095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/addresses')]</value>
      <webElementGuid>dde16bb0-e58a-4dd1-bc89-5abdf60ae696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/a</value>
      <webElementGuid>b22ed989-f9a3-4d27-97cb-2c2d2700ebdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/addresses' and (text() = 'Danh sách địa chỉ' or . = 'Danh sách địa chỉ')]</value>
      <webElementGuid>b647dfe8-2759-4d69-83cc-d8f735983fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
