<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu_form_submit-login</name>
   <tag></tag>
   <elementGuidId>c4dcff94-54c7-4f7f-97d7-1e59f8c7b6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_submit-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_submit-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79db741a-8a3a-4adf-b668-72b8026ad788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__submit btn btn-signin</value>
      <webElementGuid>f519e9be-e391-40e5-bcef-313e072d99d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1adef17f-52a9-4c9c-959c-8fe94004fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_submit-login</value>
      <webElementGuid>b093ec6b-58ca-40c8-a3c6-1867f8128a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>21d9830f-c7c2-4717-8c64-b9035022a4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_submit-login&quot;)</value>
      <webElementGuid>67edb95a-4438-40d8-8b24-8b5edb3da93e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_submit-login']</value>
      <webElementGuid>16a19ac5-6fcd-4f5f-8c6b-ffe91ddee5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[3]/div/input</value>
      <webElementGuid>2751b761-86bb-43fe-a9b5-8907d5b65339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>43a21873-6edd-4c64-a8fb-b0d9cf36d26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'form_submit-login']</value>
      <webElementGuid>8182ba04-2241-4edf-a374-def34d696a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
