<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nam</name>
   <tag></tag>
   <elementGuidId>c3f8c110-550e-44d1-adeb-c764dba64ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-gender']/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-gender > label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d63b15de-ee31-4291-a6b8-12560f365c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio2</value>
      <webElementGuid>2583d082-fa98-49c1-b91e-48b6e5c7e65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nam</value>
      <webElementGuid>6fe8473e-bfe6-4e1b-8c82-ad1c68656b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-gender&quot;)/label[2]</value>
      <webElementGuid>c71d6da2-ae26-49a4-ae2a-328e4598c0f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-gender']/label[2]</value>
      <webElementGuid>cc3c1479-6b1a-4d9f-8438-8e4ccf13beb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nữ'])[1]/following::label[1]</value>
      <webElementGuid>75b736bd-3636-4c91-98e3-ec6e2d4f4dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại trang chủ'])[1]/preceding::label[5]</value>
      <webElementGuid>7de65b8b-f419-4dbd-aada-118f60053743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi mã xác nhận'])[1]/preceding::label[5]</value>
      <webElementGuid>8b3fc841-f1d4-47e8-9171-6c39c5822fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nam']/parent::*</value>
      <webElementGuid>627d2fc3-2e96-4254-9be7-a3b2b6287eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label[2]</value>
      <webElementGuid>fd6465c0-b1e3-43e0-80ef-376f320fbbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nam' or . = 'Nam')]</value>
      <webElementGuid>efff325d-51f0-4235-a5dd-1680174613f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
