<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Danh sch a ch</name>
   <tag></tag>
   <elementGuidId>b163fe9d-36e4-4e3f-83da-680275b218ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.site_account_info > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='siteNav-account']/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed86f89c-63c2-44dc-aa4f-f5508a2c6548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/addresses</value>
      <webElementGuid>37590d0b-e6fe-419b-b16c-4381b8761619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danh sách địa chỉ</value>
      <webElementGuid>4e0420c2-6d28-47b6-b3f0-27b44485d81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNav-account&quot;)/div[@class=&quot;site_account_panel_list&quot;]/div[@class=&quot;site_account_info&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>a78e0413-647f-4887-919d-e3af60b79e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siteNav-account']/div/div/ul/li[3]/a</value>
      <webElementGuid>6589c05b-0b50-464d-bb22-96c97f35dd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Danh sách địa chỉ')]</value>
      <webElementGuid>7383d92d-d123-4cfa-b2e0-f6f7b0fdea27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản của tôi'])[1]/following::a[1]</value>
      <webElementGuid>6d9ebf35-f9ec-4af5-9426-5298725e1bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin tài khoản'])[1]/following::a[2]</value>
      <webElementGuid>e4667185-84c9-4717-975b-59def7a4eb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng xuất'])[1]/preceding::a[1]</value>
      <webElementGuid>b124c220-61c9-4c41-a5cb-c1b121c3af4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TỔNG TIỀN:'])[1]/preceding::a[5]</value>
      <webElementGuid>64a54043-4b8f-41b5-83b0-f94225962ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Danh sách địa chỉ']/parent::*</value>
      <webElementGuid>cd93034c-330e-4aec-9942-8cb219d41fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/addresses')]</value>
      <webElementGuid>c791acd8-20fa-4543-b61b-b72aebb3e39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/a</value>
      <webElementGuid>1b1819c5-7162-486e-bef5-8842259bc4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/addresses' and (text() = 'Danh sách địa chỉ' or . = 'Danh sách địa chỉ')]</value>
      <webElementGuid>199bc9a5-e7f3-419f-af31-d983f16ccdb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
