<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu_form_submit-login</name>
   <tag></tag>
   <elementGuidId>6e716320-a243-4f4a-b7d1-63f79490e25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_submit-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_submit-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd732d78-20aa-4c9a-84f1-83ac26145d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__submit btn btn-signin</value>
      <webElementGuid>3717dfcd-5d81-40a6-b8c5-9b1e1cf1274f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b67f44ff-0a42-4493-a49b-498aba1dd0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_submit-login</value>
      <webElementGuid>87670367-9fba-465b-b2b0-7e4324bac8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>0050af4b-3580-414b-b1ef-bd7e6174c717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_submit-login&quot;)</value>
      <webElementGuid>63cdd256-7229-476d-9d39-8900f852e29a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_submit-login']</value>
      <webElementGuid>e9ea556b-e45c-4ccd-8f26-b50f8a146f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[3]/div/input</value>
      <webElementGuid>28abe062-7cf0-4d5a-8e43-1a1010206b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>55bb80ce-a8bd-47af-a347-58fb1e960187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'form_submit-login']</value>
      <webElementGuid>5784452e-c0b4-442b-93e6-e42552686c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
