<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M bu chnh_customer_pick_at_location</name>
   <tag></tag>
   <elementGuidId>4c387704-bdaa-4344-91e9-c32aa3a4ed9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_pick_at_location_true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_pick_at_location_true</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b69dc1c8-0691-4bdb-99f1-7ac4eb476379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9434a336-7e3a-4f72-aebe-309412dcd065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_pick_at_location_true</value>
      <webElementGuid>779b6093-e7bd-4abf-b02e-77b005f64dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_pick_at_location</value>
      <webElementGuid>1224f9cd-2f00-4e98-a22a-55143dc11013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>69b7b1c3-1870-4313-9dc2-b1d690a8cc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edc638cb-f585-429a-9d69-fcf1bfdb516a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_pick_at_location_true&quot;)</value>
      <webElementGuid>c18f915e-4dc5-4160-bc29-75db05c401f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_pick_at_location_true']</value>
      <webElementGuid>72fab96d-f7bb-4823-acea-40d3c7c7e147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_update_shipping_method']/div/div[3]/label/div/input</value>
      <webElementGuid>190d1360-f142-42a2-9c08-90d54ff0982b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/input</value>
      <webElementGuid>045ce1c9-02d3-43de-bffc-113d4f4d9677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'customer_pick_at_location_true' and @name = 'customer_pick_at_location']</value>
      <webElementGuid>f1eb4871-6d8d-4e4a-be7f-845643a73cae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
