<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phng thc thanh ton_payment_method_id</name>
   <tag></tag>
   <elementGuidId>486cd088-4d8e-4c7f-84b6-77403efb256b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_id_1002683004']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment_method_id_1002683004</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df7147c9-9e7f-467a-9fc6-027511d59449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54440525-7a45-48a5-aca3-54a04640712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_id_1002683004</value>
      <webElementGuid>d31934e2-254a-4afa-b78c-de29b6ef52dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>8945224e-bb76-4e66-8d4e-970fa637decd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method_id</value>
      <webElementGuid>c4a0f6ea-358c-434b-a4cd-af2aeabf35f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8df6e414-ba4b-42de-9e80-ad56d50340fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1002683004</value>
      <webElementGuid>a60873f9-701d-49b0-b191-7ff41390ce8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_id_1002683004&quot;)</value>
      <webElementGuid>142cffa8-2a09-4540-8b76-ad0256b4c1d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_id_1002683004']</value>
      <webElementGuid>308545ae-0f20-40bb-a263-133afeb68071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-payment-method']/div[3]/div/div/label/div/input</value>
      <webElementGuid>49ee375e-f89b-4f20-ace5-0204fabff9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>ec7a9a42-ffc7-4084-a802-6128a51fc737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_id_1002683004' and @name = 'payment_method_id' and @type = 'radio']</value>
      <webElementGuid>013ecf59-2ab2-4ae5-ba3e-9a362cf13f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
