<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_(a ch mc nh)_fa fa-times</name>
   <tag></tag>
   <elementGuidId>27c47158-b336-463e-a390-c26eca22ff42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address_tables']/div/div/div/p/span[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4b7d1577-1340-4276-b3a4-83eb178e3472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>86ce0926-cfe7-4d48-a8be-1b771bd551f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09d738cf-5fc3-4210-a0eb-f0c0dc40622e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_tables&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-xs-12 clearfix&quot;]/div[@class=&quot;address_title&quot;]/p[@class=&quot;address_actions text-right&quot;]/span[@class=&quot;action_link action_delete&quot;]/a[1]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>06522085-228f-4ffb-947d-834884599314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address_tables']/div/div/div/p/span[2]/a/i</value>
      <webElementGuid>ae9a3625-629e-4404-8146-d04896673882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/i</value>
      <webElementGuid>51852ad2-2dd3-4d44-86e4-bbf91a30f846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
