<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Danh sch a ch</name>
   <tag></tag>
   <elementGuidId>24b96f87-d0db-4571-99ec-f811140fd4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.site_account_info > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='siteNav-account']/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ec53d94-f66d-4b88-ae88-03209ff4a39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/addresses</value>
      <webElementGuid>4e6dd252-3f88-4731-bceb-94b452fc1b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danh sách địa chỉ</value>
      <webElementGuid>09752203-dada-45f7-8099-a442579bc238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteNav-account&quot;)/div[@class=&quot;site_account_panel_list&quot;]/div[@class=&quot;site_account_info&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>d30f93da-90d7-47ce-ba34-0f9923380fe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siteNav-account']/div/div/ul/li[3]/a</value>
      <webElementGuid>8ec725f8-7381-4a17-866b-6fb32b17a96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Danh sách địa chỉ')]</value>
      <webElementGuid>328fa4e5-3d2a-4e12-9594-97530603b936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản của tôi'])[1]/following::a[1]</value>
      <webElementGuid>05abd5c8-f29d-4592-9d78-fc54f0591dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lễ Nguyễn'])[1]/following::a[2]</value>
      <webElementGuid>e25028da-f280-4ff7-ab11-aed8cf6a979e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng xuất'])[1]/preceding::a[1]</value>
      <webElementGuid>2b5f3370-4446-4e8b-9a38-af47978907a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TỔNG TIỀN:'])[1]/preceding::a[5]</value>
      <webElementGuid>0ba6d822-a2ad-46d5-854c-49bf46820bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Danh sách địa chỉ']/parent::*</value>
      <webElementGuid>57adccba-a922-45ea-b68d-5cae7bc705d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/addresses')]</value>
      <webElementGuid>5ac2fc6c-effb-49aa-b443-2e95cf5a042d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/a</value>
      <webElementGuid>82740c8c-5226-4906-bbcf-900d1125e083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/addresses' and (text() = 'Danh sách địa chỉ' or . = 'Danh sách địa chỉ')]</value>
      <webElementGuid>1f3212e2-0713-4dc0-9349-a66f9606027e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
