<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_(a ch mc nh)_fa fa-times</name>
   <tag></tag>
   <elementGuidId>1321d9cc-43c0-44a2-83e7-ff167cb4fc96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address_tables']/div/div/div/p/span[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>38ce2a45-b1f9-4bf8-9998-0d4d3fbffc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>2226f1ff-011f-4ab8-a7a6-80821b8a317f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4fa14e85-7c77-4002-ad2f-52f7434707d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_tables&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-xs-12 clearfix&quot;]/div[@class=&quot;address_title&quot;]/p[@class=&quot;address_actions text-right&quot;]/span[@class=&quot;action_link action_delete&quot;]/a[1]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>ecabfc47-e87e-440d-9e80-d72598d88096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address_tables']/div/div/div/p/span[2]/a/i</value>
      <webElementGuid>93612502-285b-400e-a126-bb8ea3e4b642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/i</value>
      <webElementGuid>ea06a8ed-5bb2-4002-9e35-e85abdc0d5a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
